feat: support using VSCE_PAT environment variable for authentication token
felipecrs/semantic-release-vsce pull request #109
Opened 2021-03-10 22:31 UTC by ewanharris

This adds support for using the VSCE_PAT environment variable supported in vsce, if both VSCE_PAT
and VSCE_TOKEN are set in the environment then VSCE_PAT is preferred. It might be worthwhile to also
introduce a log that inform the user this is happening and to only use VSCE_PAT

Closes #84

2021-03-10 23:35 UTC, felipecrs requested changes
Thank you so much for the contribution! I like your idea about informing the user about the usage of VSCE_PAT, and I even left a suggestion for you about it in the comments.

2021-03-10 23:35 UTC, felipecrs commented on lib/verify-auth.js
> +  const { VSCE_TOKEN, VSCE_PAT } = process.env;
I think we can actually transform VSCE_TOKEN into VSCE_PAT at the very beginning.

Something like

```js
if(!("VSCE_PAT" in process.env) && ("VSCE_TOKEN" in process.env)) {
  logger.log("VSCE_TOKEN is deprecated and may be removed in the next major release, use VSCE_PAT instead.")
  process.env.VSCE_PAT = process.env.VSCE_TOKEN
}

// do the rest using VSCE_PAT only
```

2021-03-10 23:35 UTC, felipecrs commented on lib/verify-auth.js
> +  if (!VSCE_TOKEN && !VSCE_PAT) {
And then here we would only have to check VSCE_PAT

2021-03-10 23:35 UTC, felipecrs commented on lib/verify-auth.js
> +    if (VSCE_TOKEN) {
and we would not need to do this `if`

2021-03-11 01:53 UTC, felipecrs commented
Also, it would be good to update the documentation.

2021-03-11 21:51 UTC, ewanharris commented
@felipecrs, checking for it and reassigning is really nice! Just pushed a change that does that and also updates the environment variable in the readme

2021-03-11 23:48 UTC, felipecrs approved these changes
Thank you so much!

2021-03-11 23:50 UTC, merged