feat: Added support for `--azure-credential` via `VSCE_USE_AZURE_CREDENTIALS` environment variable
felipecrs/semantic-release-vsce pull request #663
Opened 2024-07-26 23:15 UTC by JakeShirley

vsce added support for `--azure-credential` a few months ago as Microsoft moves away from long-living PATs.  This flag allows authentication to be pulled from the current azure cli context.

This PR also does the following small tweaks:
- Adds a `launch.json` to run ava tests for debugging via VS Code
- Fixes the test `publishes an extension in a non-root folder` to work on Windows (some hard-coded pathing assumptions were made)
- Adds a `.gitattributes` file to force line endings to be `LF` instead of `CRLF`.  On Windows prettier was complaining about all of the line endings, this change makes git clone/treat all of the files as `LF`.

I have not tested this in practice, I am not sure of the best way to do that :) 

Addresses #662

2024-07-26 23:34 UTC, felipecrs commented on lib/verify.js
> +        'No personal access token was detected. Set the `VSCE_PAT`, `VSCE_USE_AZURE_CREDENTIALS`, or the `OVSX_PAT` environment variable, at least one of them must be present when publish is enabled.
I think VSCE_AZURE_CREDENTIALS would look better.

Also, please update the documentation (README).

2024-07-27 04:59 UTC, JakeShirley commented
Validated this with my fork. Working for me! :) 

https://github.com/Mojang/minecraft-debugger/actions/runs/10120996092/job/27991427579

2024-07-27 17:45 UTC, felipecrs commented
@JakeShirley, thanks a lot. I'm currently on vacation far away from the computer.  I should review your PR next week.

2024-08-13 21:57 UTC, JakeShirley commented
@felipecrs did you ever get a chance to look at this? :)

2024-08-13 22:45 UTC, felipecrs requested changes

2024-08-13 22:45 UTC, felipecrs commented on README.md
> +| `VSCE_AZURE_CREDENTIALS` | _Optional_. When set `vsce` will use the `--azure-credential` flag to authenticate. _Note:_ Cannot be set at the same time as `VSCE_PAT`
```suggestion
| `VSCE_AZURE_CREDENTIALS` | _Optional_. When set to any value, `vsce` will use the `--azure-credential` flag to authenticate. _Note:_ Cannot be set at the same time as `VSCE_PAT`.                                                                                                                                                                        |
```

2024-08-13 22:45 UTC, felipecrs commented on README.md
> +          #VSCE_AZURE_CREDENTIALS: true
I'd rather omit this. If users want to use it, they will know how to use it. There's even your example below.

What do you think?

2024-08-13 22:45 UTC, felipecrs commented on lib/utils.js
> +  return 'VSCE_PAT' in process.env || 'VSCE_AZURE_CREDENTIALS' in process.env;
I've got to say I'm tempted to say VSCE_USE_AZURE_CREDENTIALS would be a better name, but it's not a strong opinion.

Do you have one?

2024-08-13 22:45 UTC, felipecrs commented on lib/verify-vsce-auth.js
> +  logger.log(`VSCE_AZURE_CREDENTIALS: ${process.env.VSCE_AZURE_CREDENTIALS}`);
this is more like debug. Please remove it

2024-08-13 22:45 UTC, felipecrs commented on lib/verify-vsce-auth.js
>    }
You'll have to change this a little. This actually checks whether the variable is present but empty, like: VSCE_PAT="".

Maybe you should invent two cases and two error codes? One to check for empty vsce pat and another to check for empty VSCE_AZURE_CREDENTIALS.

if ('VSCE_PAT' in process.env && !process.env.VSCE_PAT) {
  // old condition
}

// something similar for AZURE_CREDENTIALS

2024-08-13 22:45 UTC, felipecrs commented on lib/verify-vsce-auth.js
> +  if (process.env.VSCE_PAT && process.env.VSCE_AZURE_CREDENTIALS) {
```suggestion
  if ('VSCE_PAT' in process.env && 'VSCE_AZURE_CREDENTIALS' in process.env) {
```

And I think this check should come before the previous check, don't you think?

2024-08-13 22:45 UTC, felipecrs commented on lib/verify-vsce-auth.js
> +  const vsceFlags = ['verify-pat'];
```suggestion
  const vsceArgs = ['verify-pat'];
```

Or just args.

2024-08-13 22:45 UTC, felipecrs commented on package.json
> +    "@vscode/vsce": "^2.31.1",
I'll update vsce in a separate PR. You can keep this here while I do that, though.

2024-08-13 22:46 UTC, felipecrs commented
> @felipecrs did you ever get a chance to look at this? :)

Very sorry for taking this long. I had actually forgot.

2024-08-13 23:35 UTC, felipecrs commented on package.json
> +    "@vscode/vsce": "^2.31.1",
It's done, you can rebase now.

2024-08-16 17:59 UTC, felipecrs commented on lib/utils.js
> +  return 'VSCE_PAT' in process.env || 'VSCE_AZURE_CREDENTIALS' in process.env;
or actually, we should name it VSCE_AZURE_CREDENTIAL, to align with the term in vsce (--azure-credential).

2024-09-06 20:13 UTC, JakeShirley commented
@felipecrs Finally got around to addressing this feedback :)

2024-09-18 15:43 UTC, JakeShirley commented
Did a fresh rebase, hopefully all of the checks are good now :)

2024-12-27 13:19 UTC, felipecrs approved these changes

2024-12-27 13:21 UTC, merged